language: ruby
rvm:
- 2.3.0

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false