title: Historical Modeling
email: michael@qedcode.com
description: >
  An analysis and design technique for building distributed systems.
baseurl: ""
url: "http://historicalmodeling.com"
twitter_username: michaellperry
github_username:  michaellperry

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
