title: Historical Modeling
author: Michael L Perry
email: michael@qedcode.com
description: >
  An analysis and design technique for building distributed systems.
baseurl: ""
url: "http://historicalmodeling.com"
twitter_username: michaellperry
github_username:  michaellperry
copyright: 2017

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: ./_scss
exclude: [vendor]
